name       : python-google-auth
version    : 1.27.0
release    : 4
source     :
    - https://pypi.io/packages/source/g/google-auth/google-auth-1.27.0.tar.gz : da5218cbf33b8461d7661d6b4ad91c12c0107e2767904d5e3ae6408031d5463e
license    : Apache-2.0
component  : programming.python
summary    : Google Auth Python Library
description: |
    This library simplifies using Google's various server-to-server authentication mechanisms to access Google APIs.
rundeps    :
    - python-asn1-modules
    - python-cachetools
    - python-rsa
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
