name       : python-google-auth
version    : 1.6.3
release    : 2
source     :
    - https://files.pythonhosted.org/packages/ef/77/eb1d3288dbe2ba6f4fe50b9bb41770bac514cd2eb91466b56d44a99e2f8d/google-auth-1.6.3.tar.gz : 0f7c6a64927d34c1a474da92cfc59e552a5d3b940d3266606c6a28b72888b9e4
license    : Apache-2.0
component  : programming.python
summary    : Google Auth Python Library
description: |
    This library simplifies using Google's various server-to-server authentication mechanisms to access Google APIs.
rundeps    :
    - python-asn1-modules
    - python-cachetools
    - python-rsa
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
